name: Compile and run unit tests

on:
  push:
    branches:
      - 'beta.*'
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.15.0
    - name: create NPM config file
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ./.npmrc
    - run: |
        sudo apt update -y
        sudo apt install -y libudev-dev
    - run: npm run setup:ci
    - run: npm run compile
    - run: npm run test:unit
