name: Compile and run unit tests

on:
  push:
    branches:
      - 'beta.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.13.0
    - name: create NPM config file
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ./.npmrc
    - run: npm run setup
    - run: npm run compile
    - run: npm run test:main
    - run: npm run test:components
